/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class RaknetClient {
  constructor(ip?: string | undefined | null, port?: number | undefined | null, mtuSize?: number | undefined | null, debug?: boolean | undefined | null)
  connect(): void
  tick(): void
  ping(): void
  receive(): Buffer
  frameAndSend(buffer: Buffer): void
  send(buffer: Buffer): void
}
