/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsEvent {
  name: string
  data: Array<number>
}
export declare class RaknetClient {
  constructor(host: string, port: number)
  connect(): void
  receive(): Array<number>
  frameAndSend(data: Buffer): void
  tick(): void
  ping(): void
  isConnected(): boolean
  onEvent(): JsEvent | null
}
